### ISSUE TITLE
Detect click

### ISSUE THREAD

**Issue by riki-dexter** [lganzzzo/android-swipe-to-gridview#1]
Hi @lganzzzo ,
how can i detect single tap (click) on a card of gridview?
onItemClick in onInterceptTouchEvent method of SwipeToGridViewLayout is called also for starting-scroll-tap, but i'd like to call it only for single tap events.
Thank you

**Comment by lganzzzo** [comment]
Hi @riki-dexter ,

Please checkout this branch https://github.com/lganzzzo/android-swipe-to-gridview/tree/issues_1_better_touch_events.

And please let me know if it fixed the issue

Best Regards,
Leonid

**Comment by lganzzzo** [comment]
Merged to master.
Issue closed.
@riki-dexter
